removing unenrolled sites
precision-sustainable-ag/tech-dashboard pull request #636
Opened 2021-08-06 12:44 UTC by apurva-s

2021-08-06 13:10 UTC, mikahpinegar commented on src/SensorVisuals/SensorVisuals.js
> +        let response_with_filter = responseArray.filter((r) => {
should be camel cased

2021-08-06 13:12 UTC, rbandooni requested changes
Please fix the edits below

2021-08-06 13:12 UTC, rbandooni commented on src/SensorVisuals/SensorVisuals.js
> -        setLoading(false);
Why has this function been removed?

2021-08-09 14:45 UTC, mikahpinegar submitted a review, later dismissed

2021-08-09 20:38 UTC, mikahpinegar commented on src/SensorVisuals/SensorVisuals.js
> +        console.log(responseArray);
remove print

2021-08-09 21:12 UTC, apurva-s commented on src/SensorVisuals/SensorVisuals.js
> +        console.log(responseArray);
Removed the console.log

2021-08-09 21:14 UTC, rbandooni approved these changes

2021-08-09 21:18 UTC, mikahpinegar approved these changes

2021-08-09 21:19 UTC, merged