renamed edit data to edit location and added edit cash crops feature
precision-sustainable-ag/tech-dashboard pull request #928
Opened 2022-06-08 16:45 UTC by azeng4499

In Contact and Location table:

- change "Edit data" button to "Edit location"
- add a new button and modal: "Edit cash crop"
- There should be a drop down to change between Corn, Soybeans, Cotton, and Other (case and spelling matters for these)
- If they choose "Other", prompt them to make a comment to let us know what's happening
- The corrections API will be to change this value for code = XYZ, next_cash_crop = their_choice in farm_history table
- If the current value is unset (null? empty string? not sure what it will be in the response), don't fire the corrections API and instead prompt them with "Have you filled out your farm history form yet?" and let them make a comment if they have

2022-06-08 16:47 UTC, azeng4499 commented
I didn't add the change viewport functionality because the comment box gets squished for sizes sm and xs

2022-06-09 13:53 UTC, mikahpinegar requested changes

2022-06-09 13:53 UTC, mikahpinegar commented on src/SiteInformation/ContactAndLocation/EditCashCropModal.js
> +        if (cashCrop === 'Other') {
will you update state.sharedSiteInfo.valuesEdited in redux after successfully updating so that the table refreshes and gets the new data?

2022-06-09 13:53 UTC, mikahpinegar commented on src/Store/reducers/allDataTableReducer.js
> +  editLocationModalOpen: false,
valuesEdited, editLocationModalData and editLocationModalOpen actually aren't ever set in this file and should be removed from defaultState

2022-06-09 13:53 UTC, mikahpinegar commented on src/Store/reducers/sharedSiteInfoReducer.js
>      case 'SET_EDIT_MODAL_DATA':
will you change the values in the switch to match the new action names? ie SET_EDIT_MODAL_DATA -> SET_EDIT_LOCATION_MODAL_DATA etc.

2022-06-09 14:31 UTC, merged